package org.langdetect;

import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;

import org.apache.tika.language.detect.LanguageDetector;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws Exception {
        LanguageDetector detector = LanguageDetector.getDefaultLanguageDetector();
        detector.loadModels();
        
//        List<String> texts = 
                Files.list(Paths.get("src/main/resources/texts")).map(App::read)
                .forEach(t -> {
                    System.out.println(); 
                    detector.detectAll(t).forEach(System.out::println);;
                   });
                //.collect(Collectors.toList());
    }
    
    private static String read(Path path) {
        try {
            byte[] bytes = Files.readAllBytes(path);
            return new String(bytes, Charset.forName("utf8"));
        } catch (IOException e) {
            return "";
        }
    }
}
